namespace BodyOutfitPresetDB.Sliders
{
    public static class Constants
    {
        public static readonly string[] SliderNames3BA = [
            "7B Lower",
            "7B Upper",
            "7BLeg_v2",
            "AnalLoose_v2",
            "AnalPosition_v2",
            "AnalTexPosRe_v2",
            "AnalTexPos_v2",
            "AnkleSize",
            "AppleCheeks",
            "AreolaPull_v2",
            "AreolaSize",
            "ArmpitShape_v2",
            "Arms",
            "Back",
            "BackArch",
            "BackValley_v2",
            "BackWing_v2",
            "Belly",
            "BellyFrontDownFat_v2",
            "BellyFrontUpFat_v2",
            "BellySideDownFat_v2",
            "BellySideUpFat_v2",
            "BellyUnder_v2",
            "BigBelly",
            "BigButt",
            "BigTorso",
            "BreastCenter",
            "BreastCenterBig",
            "BreastCleavage",
            "BreastFlatness",
            "BreastFlatness2",
            "BreastGravity2",
            "BreastHeight",
            "BreastPerkiness",
            "BreastSideShape",
            "BreastTopSlope",
            "BreastUnderDepth",
            "BreastWidth",
            "Breasts",
            "BreastsConverage_v2",
            "BreastsFantasy",
            "BreastsGone",
            "BreastsNewSH",
            "BreastsNewSHSymmetry",
            "BreastsPressed_v2",
            "BreastsSmall",
            "BreastsSmall2",
            "BreastsTogether",
            "Butt",
            "ButtClassic",
            "ButtCrack",
            "ButtDimples",
            "ButtNarrow_v2",
            "ButtPressed_v2",
            "ButtSaggy_v2",
            "ButtShape2",
            "ButtSmall",
            "ButtUnderFold",
            "CBPC",
            "CalfFBThicc_v2",
            "CalfSize",
            "CalfSmooth",
            "ChestDepth",
            "ChestWidth",
            "ChubbyArms",
            "ChubbyButt",
            "ChubbyLegs",
            "ChubbyWaist",
            "Clavicle_v2",
            "Clit",
            "ClitSwell_v2",
            "CrotchBack",
            "CrotchGap",
            "Cutepuffyness",
            "DoubleMelon",
            "FeetFeminine",
            "ForearmSize",
            "Groin",
            "HipBone",
            "HipCarved",
            "HipForward",
            "HipNarrow_v2",
            "HipUpperWidth",
            "Hips",
            "Innieoutie",
            "KneeHeight",
            "KneeShape",
            "KneeTogether_v2",
            "LabiaBulgogi_v2",
            "LabiaCrumpled_v2",
            "LabiaMorePuffyness_v2",
            "LabiaNeat_v2",
            "LabiaTightUp",
            "Labiaprotrude",
            "Labiaprotrude2",
            "Labiaprotrudeback",
            "Labiapuffyness",
            "Labiaspread",
            "LegShapeClassic",
            "LegSpread_v2",
            "LegsThin",
            "MuscleAbs",
            "MuscleArms",
            "MuscleBack_v2",
            "MuscleButt",
            "MuscleLegs",
            "MuscleMoreAbs_v2",
            "MuscleMoreArms_v2",
            "MuscleMoreLegs_v2",
            "MusclePecs",
            "NavelEven",
            "NeckSeam",
            "NipBGone",
            "NippleBump_v2",
            "NippleCrease_v2",
            "NippleCrumpled_v2",
            "NippleDip",
            "NippleDistance",
            "NippleDown",
            "NippleInvert_v2",
            "NippleLength",
            "NippleManga",
            "NipplePerkManga",
            "NipplePerkiness",
            "NipplePuffy_v2",
            "NippleShy_v2",
            "NippleSize",
            "NippleSquash1_v2",
            "NippleSquash2_v2",
            "NippleThicc_v2",
            "NippleTip",
            "NippleTipManga",
            "NippleTube_v2",
            "NippleUp",
            "OldBaseShape",
            "PregnancyBelly",
            "PushUp",
            "RibsMore_v2",
            "RibsProminance",
            "RoundAss",
            "ShoulderSmooth",
            "ShoulderTweak",
            "ShoulderWidth",
            "SlimThighs",
            "SternumDepth",
            "SternumHeight",
            "ThighFBThicc_v2",
            "ThighInsideThicc_v2",
            "ThighOutsideThicc_v2",
            "Thighs",
            "TummyTuck",
            "UNPHip_v2",
            "VaginaHole",
            "Vaginasize",
            "VanillaSSEHi",
            "VanillaSSELo",
            "Waist",
            "WaistHeight",
            "WideWaistLine",
            "WristSize"];

        public static readonly HashSet<string> InvertedSliders =
            new(StringComparer.OrdinalIgnoreCase)
            {
                "BreastsSmall",
                "BreastsSmall2",
                "BreastFlatness",
                "BreastFlatness2",
                "BreastsPressed_v2",
                "BreastsGone",
                "BreastPerkiness",
                "BreastGravity2",
                "NipBGone",
                "ButtSmall",
                "ButtNarrow_v2",
                "ButtPressed_v2",
                "HipNarrow_v2"
            };

        public static readonly Dictionary<string, float> SliderWeights =
            new(StringComparer.OrdinalIgnoreCase)
            {
                // --- Breasts ---
                ["BreastsNewSH"] = 1.4f,
                ["BreastsNewSHSymmetry"] = 0.01f,
                ["BreastsTogether"] = 0.1f,
                ["BreastsCleavage"] = 0.3f,
                ["Breasts"] = 1.2f,
                ["BreastsSmall"] = 1.4f,
                ["BreastsSmall2"] = 1.4f,
                ["DoubleMelon"] = 1.3f,
                ["BreastsFantasy"] = 1.3f,
                ["BreastFlatness"] = 3.0f,
                ["BreastFlatness2"] = 3.0f,
                ["BreastsGone"] = 3.0f,
                ["BreastHeight"] = 0.05f,
                ["BreastWidth"] = 0.1f,
                ["BreastCenter"] = 0.01f,
                ["BreastCenterBig"] = 0.01f,
                ["BreastUnderDepth"] = 0.01f,
                ["BreastSideShape"] = 0.01f,
                ["BreastTopSlope"] = 0.2f,
                ["BreastsConverage_v2"] = 0.2f,
                ["PushUp"] = 0.2f,
                ["BreastGravity2"] = 0.7f,

                // --- Full Body ---
                ["7B Upper"] = 1.4f,
                ["7B Lower"] = 1.4f,
                ["7BLeg_v2"] = 1.3f,
                ["OldBaseShape"] = 1.6f,
                ["VanillaSSEHi"] = 1.5f,
                ["VanillaSSELo"] = 1.3f,

                // --- Butt ---
                ["Butt"] = 1.2f,
                ["ButtSmall"] = 1.0f,
                ["BigButt"] = 1.2f,
                ["ChubbyButt"] = 1.2f,
                ["AppleCheeks"] = 1.2f,

                // --- Torso ---
                ["BigTorso"] = 1.4f,
                ["ChubbyWaist"] = 1.4f,

                // --- Legs and Feet ---
                ["ChubbyLegs"] = 1.4f,

                // --- Belly ---
                ["Belly"] = 1.2f,
                ["BigBelly"] = 1.4f,
                ["PregnancyBelly"] = 1.8f,

                // --- Muscle Definition ---
                ["MuscleAbs"] = 0.2f,
                ["MuscleArms"] = 0.1f,
                ["MuscleButt"] = 0.1f,
                ["MuscleLegs"] = 0.2f,
                ["MusclePecs"] = 0.3f,
                ["MuscleMoreAbs_v2"] = 2.0f,
                ["MuscleMoreArms_v2"] = 2.0f,
                ["MuscleMoreLegs_v2"] = 2.0f,
                ["MuscleBack_v2"] = 2.0f,

                // --- Defaults ---
                // anything not listed → 1.0
            };
    }
}
